### ISSUE TITLE
Invalid Signature when getting all orders of a certain product

### ISSUE THREAD

**Issue by abir-taheer** [bennycode/coinbase-pro-node#471] opened 2021-04-21 17:01 UTC
In my code I'm trying to get all of my orders for a certain crypto currency and when I do, it throws a 401 error with the message `invalid signature`.

For more information, this is my code:

The product id I used was `LTC-USD` but it doesn't work with any I've tried.
```javascript
const orders = await client.rest.order.getOrders({
  status: ["all"],
  product_id: productId,
});
```

Surprisingly, it works if I omit the `product_id` parameter.
```javascript
const orders = await client.rest.order.getOrders({
  status: ["all"],
});
```
That works and returns a paginated result with all my orders.

I don't think I'm doing anything wrong?

**Comment by bennycode** [comment] 2021-04-25 17:56
@abir-taheer thanks for your report! I was able to reproduce the problem and realized that filtering by `status` and `product_id` are mutually exclusive. I created a fix for it to express this in TypeScript: https://github.com/bennycode/coinbase-pro-node/pull/475

I also extended the request timeout because it can happen that requests easily take up to 25 seconds when all order types are requested.

The fix got released with v3.0.3. 🤙

**Closed by bennycode** 2021-04-25 17:56 UTC
